<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../RaftBroker.Core/RaftBroker.Core.csproj" />
    <ProjectReference Include="../RaftBroker.Storage/RaftBroker.Storage.csproj" />
    <ProjectReference Include="../RaftBroker.Raft/RaftBroker.Raft.csproj" />
    <ProjectReference Include="../RaftBroker.StateMachine/RaftBroker.StateMachine.csproj" />
    <ProjectReference Include="../RaftBroker.Transport/RaftBroker.Transport.csproj" />
  </ItemGroup>

</Project>
